class Power:
    LOAD = 0
    SYNCHRONOUS_GENERATOR = 1
    BUS = 2
    UTILITY = 3

    TWO_WINDING_TRANSFORMER = 0
    DIRECT_CONNECTION = 1
    CABLE = 2
    OVERHEAD_LINE = 3


class Load:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    IS_BUS = 3
    VOLTAGE_1_MAGNITUDE = 4
    VOLTAGE_1_ANGLE = 5
    VOLTAGE_1_PU = 6
    TYPE = 7
    LATITUDE = 8
    LONGITUDE = 9
    POWER_RATING = 12
    POWER_FACTOR_PERCENT = 13
    POWER_FACTOR_TYPE = 14
    MIN_PU_VOLTAGE = 15
    WIRING = 16
    LOAD_MODEL = 17
    CURRENT_RATING = 18
    NOMINAL_LL_VOLTAGE = 19
    CURRENT_1_MAGNITUDE = 20
    CURRENT_1_ANGLE = 21
    REAL_POWER = 22
    REACTIVE_POWER = 23


class SynchronousGenerator:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    IS_BUS = 3
    VOLTAGE_1_MAGNITUDE = 4
    VOLTAGE_1_ANGLE = 5
    VOLTAGE_1_PU = 6
    TYPE = 7
    LATITUDE = 8
    LONGITUDE = 9
    STIFFNESS = 12
    POWER_RATING = 13
    RPM_RATING = 14
    NUMBER_OF_POLES = 15
    POWER_FACTOR_PERCENT = 16
    WIRING = 17
    NOMINAL_LL_VOLTAGE = 18
    CURRENT_1_MAGNITUDE = 19
    CURRENT_1_ANGLE = 20
    REAL_POWER = 21
    REACTIVE_POWER = 22


class Bus:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    IS_BUS = 3
    VOLTAGE_1_MAGNITUDE = 4
    VOLTAGE_1_ANGLE = 5
    VOLTAGE_1_PU = 6
    TYPE = 7
    LATITUDE = 8
    LONGITUDE = 9
    NOMINAL_LL_VOLTAGE = 12


class Utility:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    IS_BUS = 3
    VOLTAGE_1_MAGNITUDE = 4
    VOLTAGE_1_ANGLE = 5
    VOLTAGE_1_PU = 6
    TYPE = 7
    LATITUDE = 8
    LONGITUDE = 9
    BASE_POWER = 12
    LL_VOLTAGE = 13
    VOLTAGE_ANGLE = 14
    SHORT_CIRCUIT_3_PHASE = 15
    SHORT_CIRCUIT_SLG = 16
    STIFFNESS = 17
    R_1 = 18
    X_1 = 19
    R_0 = 20
    X_0 = 21
    CURRENT_1_MAGNITUDE = 22
    CURRENT_1_ANGLE = 23


class TwoWindingTransformer:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    CURRENT_1_MAGNITUDE = 3
    CURRENT_1_ANGLE = 4
    REAL_POWER_ENTERING = 5
    REACTIVE_POWER_ENTERING = 6
    REAL_POWER_LEAVING = 7
    REACTIVE_POWER_LEAVING = 8
    TYPE = 9
    FROM_BUS = 10
    TO_BUS = 11
    FROM_BUS_VOLTAGE_RATING = 14
    TO_BUS_VOLTAGE_RATING = 15
    FROM_BUS_WIRING = 16
    TO_BUS_WIRING = 17
    POWER_RATING = 18
    X_PERCENT = 19
    R_PERCENT = 20
    TAP_PERCENT = 21
    TAP_SIDE = 22
    MIN_TAP = 23
    MAX_TAP = 24


class DirectConnection:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    CURRENT_1_MAGNITUDE = 3
    CURRENT_1_ANGLE = 4
    REAL_POWER_ENTERING = 5
    REACTIVE_POWER_ENTERING = 6
    REAL_POWER_LEAVING = 7
    REACTIVE_POWER_LEAVING = 8
    TYPE = 9
    FROM_BUS = 10
    TO_BUS = 11
    FROM_BUS_VOLTAGE_RATING = 14
    TO_BUS_VOLTAGE_RATING = 15


class Cable:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    CURRENT_1_MAGNITUDE = 3
    CURRENT_1_ANGLE = 4
    REAL_POWER_ENTERING = 5
    REACTIVE_POWER_ENTERING = 6
    REAL_POWER_LEAVING = 7
    REACTIVE_POWER_LEAVING = 8
    TYPE = 9
    FROM_BUS = 10
    TO_BUS = 11
    LINECODE_OBJECT_ID = 14
    VOLTAGE_RATING = 15
    LENGTH = 16
    NUMBER_OF_CABLES = 17


class OverheadLine:
    ID = 0
    NAME = 1
    OPERATIONAL_STATUS = 2
    CURRENT_1_MAGNITUDE = 3
    CURRENT_1_ANGLE = 4
    REAL_POWER_ENTERING = 5
    REACTIVE_POWER_ENTERING = 6
    REAL_POWER_LEAVING = 7
    REACTIVE_POWER_LEAVING = 8
    TYPE = 9
    FROM_BUS = 10
    TO_BUS = 11
    WIREDATA_OBJECT_ID = 14
    NUMBER_OF_CONDUCTORS = 15
    LENGTH = 16
    SOIL_RESISTIVITY = 17
    X_1 = 18
    X_2 = 19
    X_3 = 20
    Y_1 = 21
    Y_2 = 22
    Y_3 = 23
    H_1 = 24
    H_2 = 25
    H_3 = 26
    X_4 = 27
    Y_4 = 28
    H_4 = 29
    NOMINAL_LL_VOLTAGE = 30


class WireData:
    ID = 0
    NAME = 1
    RESISTANCE_50_C = 2
    CONTINUOUS_AMPACITY = 3
    EMERGENCY_AMPACITY = 4
    DIAMETER = 5
    GMR = 6
    TYPE = 7
    WIRE_TYPE = 8


class WireType:
    PHASE = 0
    NEUTRAL = 1
