# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.BooleanField(default=True)),
                ('is_bus', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0, max_length=50)),
                ('longitude', models.FloatField(default=0, max_length=50)),
                ('name', models.CharField(default='Untitled Bus', max_length=100)),
                ('nominal_LL_voltage', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_magnitude', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_angle', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_PU', models.FloatField(default=0.0, max_length=100)),
                ('a_created_date', models.BigIntegerField(default=1457583800.3097465)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(default=0)),
                ('to_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('created_date', models.BigIntegerField(default=1457583800.2941206)),
            ],
        ),
        migrations.CreateModel(
            name='DBChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_check', models.BigIntegerField(default=1457583800.2941206)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.BooleanField(default=True)),
                ('is_bus', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0, max_length=50)),
                ('longitude', models.FloatField(default=0, max_length=50)),
                ('name', models.CharField(default='Untitled Load', max_length=100)),
                ('voltage_rating', models.FloatField(default=0.0, max_length=100)),
                ('current_rating', models.FloatField(default=0.0, max_length=100)),
                ('power_rating', models.FloatField(default=0.0, max_length=100)),
                ('power_factor_percent', models.FloatField(default=0.0, max_length=100)),
                ('power_factor_type', models.IntegerField(default=0)),
                ('min_PU_voltage', models.FloatField(default=0.0, max_length=100)),
                ('wiring', models.IntegerField(default=0)),
                ('load_model', models.IntegerField(default=0)),
                ('nominal_LL_voltage', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_magnitude', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_angle', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_PU', models.FloatField(default=0.0, max_length=100)),
                ('a_current_magnitude', models.FloatField(default=0.0, max_length=100)),
                ('a_current_angle', models.FloatField(default=0.0, max_length=100)),
                ('P', models.FloatField(default=0.0, max_length=100)),
                ('Q', models.FloatField(default=0.0, max_length=100)),
                ('created_date', models.BigIntegerField(default=1457583800.2941206)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SyncGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.BooleanField(default=True)),
                ('is_bus', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0, max_length=50)),
                ('longitude', models.FloatField(default=0, max_length=50)),
                ('name', models.CharField(default='Untitled Sync Gen', max_length=100)),
                ('power_rating', models.FloatField(default=0.0, max_length=100)),
                ('LL_voltage', models.FloatField(default=0.0, max_length=100)),
                ('RPM_rating', models.IntegerField(default=0.0)),
                ('pole_count', models.IntegerField(default=0.0)),
                ('pf_percent', models.FloatField(default=0.0, max_length=100)),
                ('wiring', models.IntegerField(default=0)),
                ('a_voltage_magnitude', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_angle', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_PU', models.FloatField(default=0.0, max_length=100)),
                ('a_current_magnitude', models.FloatField(default=0.0, max_length=100)),
                ('a_current_angle', models.FloatField(default=0.0, max_length=100)),
                ('P', models.FloatField(default=0.0, max_length=100)),
                ('Q', models.FloatField(default=0.0, max_length=100)),
                ('created_date', models.BigIntegerField(default=1457583800.2941206)),
            ],
        ),
        migrations.CreateModel(
            name='TwoWindingTransformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.BooleanField(default=True)),
                ('is_bus', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0, max_length=50)),
                ('longitude', models.FloatField(default=0, max_length=50)),
                ('from_bus', models.IntegerField(default=0)),
                ('to_bus', models.IntegerField(default=0)),
                ('name', models.CharField(default='Untitled TWTransformer', max_length=100)),
                ('base_power', models.FloatField(default=0.0, max_length=100)),
                ('created_date', models.BigIntegerField(default=1457583800.3097465)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.BooleanField(default=True)),
                ('is_bus', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0, max_length=50)),
                ('longitude', models.FloatField(default=0, max_length=50)),
                ('name', models.CharField(default='Untitled Utility', max_length=100)),
                ('LL_voltage', models.FloatField(default=0.0, max_length=100)),
                ('voltage_angle', models.FloatField(default=0.0, max_length=100)),
                ('short_circuit_3_phase', models.FloatField(default=0.0, max_length=100)),
                ('short_circuit_SLG', models.FloatField(default=0.0, max_length=100)),
                ('x_r_ratio_positive', models.FloatField(default=0.0, max_length=100)),
                ('x_r_ratio_zero', models.FloatField(default=0.0, max_length=100)),
                ('x_positive', models.FloatField(default=0.0, max_length=100)),
                ('x_zero', models.FloatField(default=0.0, max_length=100)),
                ('r_positive', models.FloatField(default=0.0, max_length=100)),
                ('r_zero', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_magnitude', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_angle', models.FloatField(default=0.0, max_length=100)),
                ('a_voltage_PU', models.FloatField(default=0.0, max_length=100)),
                ('a_current_magnitude', models.FloatField(default=0.0, max_length=100)),
                ('a_current_angle', models.FloatField(default=0.0, max_length=100)),
                ('a_created_date', models.BigIntegerField(default=1457583800.3097465)),
            ],
        ),
    ]
