# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='is_bus',
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1460732750.392323),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1460732750.390523),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_date',
            field=models.BigIntegerField(default=1460732750.391408),
        ),
    ]
