# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160217_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='created_date',
            field=models.BigIntegerField(default=1456171673.716101),
        ),
    ]
