# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160325_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiredata',
            old_name='neutral_continuous_ampacity',
            new_name='continuous_ampacity',
        ),
        migrations.RenameField(
            model_name='wiredata',
            old_name='neutral_diameter',
            new_name='diameter',
        ),
        migrations.RenameField(
            model_name='wiredata',
            old_name='neutral_emergency_ampacity',
            new_name='emergency_ampacity',
        ),
        migrations.RenameField(
            model_name='wiredata',
            old_name='neutral_resistance_50_C',
            new_name='resistance_50_C',
        ),
        migrations.RemoveField(
            model_name='wiredata',
            name='neutral_GMR',
        ),
        migrations.RemoveField(
            model_name='wiredata',
            name='phase_GMR',
        ),
        migrations.RemoveField(
            model_name='wiredata',
            name='phase_continuous_ampacity',
        ),
        migrations.RemoveField(
            model_name='wiredata',
            name='phase_diameter',
        ),
        migrations.RemoveField(
            model_name='wiredata',
            name='phase_emergency_ampacity',
        ),
        migrations.RemoveField(
            model_name='wiredata',
            name='phase_resistance_50_C',
        ),
        migrations.AddField(
            model_name='wiredata',
            name='GMR',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='wiredata',
            name='type',
            field=models.CharField(default='Untitled Node', max_length=100),
        ),
        migrations.AddField(
            model_name='wiredata',
            name='wire_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1458944248.0308435),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1458944248.0308435),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_date',
            field=models.BigIntegerField(default=1458944248.0308435),
        ),
    ]
