# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160310_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='a_created_date',
        ),
        migrations.RemoveField(
            model_name='utility',
            name='a_created_date',
        ),
        migrations.AddField(
            model_name='bus',
            name='created_date',
            field=models.BigIntegerField(default=1457663480.7551014),
        ),
        migrations.AddField(
            model_name='utility',
            name='created_date',
            field=models.BigIntegerField(default=1457663480.7551014),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1457663480.7551014),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1457663480.7551014),
        ),
        migrations.AlterField(
            model_name='load',
            name='created_date',
            field=models.BigIntegerField(default=1457663480.7551014),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='UN', max_length=100),
        ),
        migrations.AlterField(
            model_name='syncgenerator',
            name='created_date',
            field=models.BigIntegerField(default=1457663480.7551014),
        ),
        migrations.AlterField(
            model_name='twowindingtransformer',
            name='created_date',
            field=models.BigIntegerField(default=1457663480.7551014),
        ),
    ]
