# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160220_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.BigIntegerField(default=1456105108.527906)),
            ],
        ),
        migrations.AlterField(
            model_name='power',
            name='created_date',
            field=models.BigIntegerField(default=1456105108.527906),
        ),
    ]
