# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160310_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='created_date',
            field=models.BigIntegerField(default=1457984671.564305),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1457984671.560327),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1457984671.558835),
        ),
        migrations.AlterField(
            model_name='load',
            name='created_date',
            field=models.BigIntegerField(default=1457984671.561718),
        ),
        migrations.AlterField(
            model_name='syncgenerator',
            name='created_date',
            field=models.BigIntegerField(default=1457984671.563156),
        ),
        migrations.AlterField(
            model_name='twowindingtransformer',
            name='created_date',
            field=models.BigIntegerField(default=1457984671.566376),
        ),
        migrations.AlterField(
            model_name='utility',
            name='created_date',
            field=models.BigIntegerField(default=1457984671.565434),
        ),
    ]
