# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160325_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='nominal_LL_voltage',
            new_name='nominal_voltage',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='nominal_LL_voltage',
            new_name='nominal_voltage',
        ),
        migrations.RenameField(
            model_name='syncgenerator',
            old_name='nominal_LL_voltage',
            new_name='nominal_voltage',
        ),
        migrations.RenameField(
            model_name='utility',
            old_name='LL_voltage',
            new_name='nominal_voltage',
        ),
        migrations.AddField(
            model_name='node',
            name='LL_voltage',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1459035492.9476547),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1459035492.9456522),
        ),
        migrations.AlterField(
            model_name='linecode',
            name='name',
            field=models.CharField(default='Untitled Line', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_date',
            field=models.BigIntegerField(default=1459035492.9466538),
        ),
        migrations.AlterField(
            model_name='overheadline',
            name='wiredata_object_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wiredata',
            name='name',
            field=models.CharField(default='Untitled Wire', max_length=100),
        ),
        migrations.AlterField(
            model_name='wiredata',
            name='type',
            field=models.CharField(default='Unknown Type', max_length=100),
        ),
    ]
