# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20160221_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbchanges',
            name='update',
        ),
        migrations.AddField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1456106227.7406194),
        ),
        migrations.AlterField(
            model_name='power',
            name='created_date',
            field=models.BigIntegerField(default=1456106227.7406194),
        ),
    ]
