# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20160319_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='f_id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='created_date',
            field=models.BigIntegerField(default=1458429734.0922153),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1458429734.0922153),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1458429734.0922153),
        ),
        migrations.AlterField(
            model_name='load',
            name='created_date',
            field=models.BigIntegerField(default=1458429734.0922153),
        ),
        migrations.AlterField(
            model_name='syncgenerator',
            name='created_date',
            field=models.BigIntegerField(default=1458429734.0922153),
        ),
        migrations.AlterField(
            model_name='twowindingtransformer',
            name='created_date',
            field=models.BigIntegerField(default=1458429734.0922153),
        ),
        migrations.AlterField(
            model_name='utility',
            name='created_date',
            field=models.BigIntegerField(default=1458429734.0922153),
        ),
    ]
