# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20160221_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1456112004.5632),
        ),
        migrations.AlterField(
            model_name='power',
            name='created_date',
            field=models.BigIntegerField(default=1456112004.5626998),
        ),
    ]
