# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20160326_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Node')),
                ('elevation', models.FloatField(default=0.0, max_length=100)),
                ('net_inflow', models.FloatField(default=0.0, max_length=100)),
                ('water_age', models.FloatField(default=0, max_length=100)),
            ],
            bases=('client.node',),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1459364740.160939),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1459364740.159388),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_date',
            field=models.BigIntegerField(default=1459364740.160126),
        ),
    ]
