# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20160319_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Connection')),
                ('linecode_object_id', models.IntegerField(default=0)),
                ('voltage_rating', models.FloatField(default=0.0, max_length=100)),
                ('length', models.FloatField(default=0.0, max_length=100)),
                ('number_of_cables', models.IntegerField(default=0)),
            ],
            bases=('client.connection',),
        ),
        migrations.CreateModel(
            name='DirectConnection',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Connection')),
                ('from_bus_voltage_rating', models.FloatField(default=0.0, max_length=100)),
                ('to_bus_voltage_rating', models.FloatField(default=0.0, max_length=100)),
            ],
            bases=('client.connection',),
        ),
        migrations.CreateModel(
            name='OverheadLine',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Connection')),
                ('wiredata_object_id', models.IntegerField(default=0)),
                ('number_of_conductors', models.IntegerField(default=0)),
                ('length', models.FloatField(default=0.0, max_length=100)),
                ('soil_resistivity', models.FloatField(default=0.0, max_length=100)),
                ('kron_reduction', models.BooleanField(default=True)),
                ('nominal_LL_voltage', models.FloatField(default=0.0, max_length=100)),
            ],
            bases=('client.connection',),
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_units', models.IntegerField(default=0)),
                ('ambient_temp_celsius', models.FloatField(default=0, max_length=100)),
                ('ambient_temp_fahrenheit', models.FloatField(default=0, max_length=100)),
                ('voltage_units', models.IntegerField(default=0)),
                ('current_units', models.IntegerField(default=0)),
                ('power_units', models.IntegerField(default=0)),
                ('base_frequency', models.IntegerField(default=0)),
                ('bus_count', models.IntegerField(default=0)),
                ('utility_count', models.IntegerField(default=0)),
                ('generator_count', models.IntegerField(default=0)),
                ('load_count', models.IntegerField(default=0)),
                ('transformer_count', models.IntegerField(default=0)),
                ('branch_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='twowindingtransformer',
            old_name='base_power',
            new_name='power_rating',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='to_id',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='from_bus',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='is_bus',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='operational_status',
        ),
        migrations.RemoveField(
            model_name='twowindingtransformer',
            name='to_bus',
        ),
        migrations.AddField(
            model_name='connection',
            name='current_1_angle',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='current_1_magnitude',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='from_bus_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(default='Untitled Connection', max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='operational_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='reactive_power_entering',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='reactive_power_leaving',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='real_power_entering',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='real_power_leaving',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_bus_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='connection_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Connection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='from_bus_voltage_rating',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='from_bus_wiring',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='max_tap',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='min_tap',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='r_percent',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='tap_percent',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='tap_side',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='to_bus_voltage_rating',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='to_bus_wiring',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twowindingtransformer',
            name='x_percent',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1458517687.5058517),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1458517687.5043504),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_date',
            field=models.BigIntegerField(default=1458517687.5053513),
        ),
    ]
