# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20160320_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.BigIntegerField(default=1458518331.1902604),
        ),
        migrations.AlterField(
            model_name='dbchanges',
            name='update_check',
            field=models.BigIntegerField(default=1458518331.1892593),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_date',
            field=models.BigIntegerField(default=1458518331.1892593),
        ),
    ]
